### ISSUE TITLE
Small issue with code from blog post

### ISSUE THREAD

**Issue by tannerdolby** [binyamin/binyam.in#26]
Hey, Binyamin. I read your article [Filter Posts by tag](https://binyam.in/blog/filter-posts-by-tag/) and implemented the search by `data-tags` feature on my site. It works great!

I did notice one minor issue. When attempting to use `filter` on the NodeList from `querySelectorAll`, it throws an error that `posts` is not a generic array and doesn't have access to array methods like `filter` (since its a NodeList).

```
const posts = document.querySelectorAll(".post");
...
let postsNoTag = posts.filter(l => {
        return JSON.parse(l.dataset.tags).includes(tag) === false;
    });
```

### Solution 1:
Convert the `posts` NodeList (which is iterable) into an array 
```
const posts = [...document.querySelectorAll(".post")];
```

### Solution 2:
Apply `filter` on the static results of the posts NodeList
```
let postsNoTag = Array.prototype.filter.call(posts, function(l) {
        return JSON.parse(l.dataset.tags).includes(tag) === false;
    });

```

### Solution 3:
Use the good ole `Array.from()` method.
```
const posts = Array.from(document.querySelectorAll(".post");
```

Maybe something to note in the article, or just update to one of the above solutions. Let me know your thoughts @binyamin

**Comment by binyamin** [comment]
@tannerdolby Good catch! I prefer version one. What are your thoughts?

**Comment by tannerdolby** [comment]
@binyamin Thanks! I prefer the first version as well. 

All three of the solutions are viable and of relatively equal performance, but all we really need to do is make the iterable NodeList object into an array. Which is why I think `[...document.querySelectorAll(".posts")]` is probably the best. 

It only requires the spread syntax `...` and an array literal `[...]`. Using `Array.from()` would be fine, but option 1 makes the most sense (especially if people aren't familiar with iterable NodeList objects, which aren't genuine arrays that can't use generic array methods).

**Comment by binyamin** [comment]
@tannerdolby Thanks so much!
